version: '3.8'
services:

  api:
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: digi-school/api:latest
    container_name: api
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mongoDbTp

  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: digi-school/mongodb:latest
    container_name: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db/data:/data/db
    networks:
      - mongoDbTp
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

networks:
  mongoDbTp:
    driver: bridge

volumes:
  mongodb-data:
    

