version: '3'
services:
  
  school-api:
      build: 
        context: ./app
        dockerfile: Dockerfile
      container_name: school-api
      volumes:
        - ./app:/app
      ports:
        - "8000:8000"
      depends_on:
        mongodb:
          condition: service_healthy

  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db/data:/data/db
    networks:
      - mongoDbTp
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

networks:
  mongoDbTp:
    driver: bridge

volumes:
  mongodb-data:

