FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
 
RUN apt-get update
 
WORKDIR /app
 
COPY . /app
 
 
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
 
COPY . .
 
ENV PYTHONPATH=/app
 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
