FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

LABEL maintainer="Kieran & Fabrice"
 
RUN apt-get update
 
WORKDIR /app
 
COPY . /app
 
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
 
ENV PYTHONPATH=/app
 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
